services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dropfiles_api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: postgres:16-alpine
    container_name: dropfiles_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dropfiles
      POSTGRES_USER: dropfiles
      POSTGRES_PASSWORD: dropfiles
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: